server:
  port: 8080
  servlet:
    context-path: /zbq
  
#spring:
#    datasource:
#        name: test
#        driver-class-name: com.mysql.cj.jdbc.Driver
#        url: jdbc:mysql://101.132.176.149:3306/afc_db?useUnicode=true&characterEncoding=utf8
#        username: root
#        password: jvNpppypKeJWg22r
#
#mybatis:
#  mapper-locations: classpath:com/grg/model/sqlmap/*.xml
#  type-aliases-package: com.grg.model.entity
#
#pagehelper:
#    helperDialect: mysql
#    reasonable: true
#    supportMethodsArguments: true
#    params: count=countSql
 
 # redis配置
#redis:
#  database: 1
#  host: 127.0.0.1
#  port: 6379
#  password: GRGbanking@2019
#  jedis:
#    pool:
#      max-active: 300
#      max-wait: 30000
#      max-idle: 10
#      min-idle: 10
#  timeout: 10000
 
 
 
logging:
  level:
    com.grg.dao : debug
    
  