package com.zbq.model.entity.req;

import java.io.Serializable;
import java.util.Date;

public class ReqTVM implements Serializable {
   
    private String ver;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column reqbasedatetvm.requestDate
     *
     * @mbg.generated Fri Dec 07 14:58:27 CST 2018
     */
    private String requestDate;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column reqbasedatetvm.station
     *
     * @mbg.generated Fri Dec 07 14:58:27 CST 2018
     */
   
    private String deviceId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column reqbasedatetvm.devStatus
     *
     * @mbg.generated Fri Dec 07 14:58:27 CST 2018
     */
    private String devStatus;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column reqbasedatetvm.noteAcceptSt
     *
     * @mbg.generated Fri Dec 07 14:58:27 CST 2018
     */
    private String noteAcceptSt;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column reqbasedatetvm.coinAcceptSt
     *
     * @mbg.generated Fri Dec 07 14:58:27 CST 2018
     */
    private String coinAcceptSt;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column reqbasedatetvm.sjtAcceptSt
     *
     * @mbg.generated Fri Dec 07 14:58:27 CST 2018
     */
    private String sjtSaleSt;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column reqbasedatetvm.changedSt
     *
     * @mbg.generated Fri Dec 07 14:58:27 CST 2018
     */
    private String changedSt;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column reqbasedatetvm.sjiMOduleSt
     *
     * @mbg.generated Fri Dec 07 14:58:27 CST 2018
     */
    private String sjiMOduleSt;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column reqbasedatetvm.noteModuleSt
     *
     * @mbg.generated Fri Dec 07 14:58:27 CST 2018
     */
    private String noteModuleSt;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column reqbasedatetvm.noteBoxSt
     *
     * @mbg.generated Fri Dec 07 14:58:27 CST 2018
     */
    private String noteBoxSt;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column reqbasedatetvm.coinModuleSt
     *
     * @mbg.generated Fri Dec 07 14:58:27 CST 2018
     */
    private String coinModuleSt;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column reqbasedatetvm.coinBoxSt
     *
     * @mbg.generated Fri Dec 07 14:58:27 CST 2018
     */
    private String coinBoxSt;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column reqbasedatetvm.touchSt
     *
     * @mbg.generated Fri Dec 07 14:58:27 CST 2018
     */
    private String touchSt;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column reqbasedatetvm.mantMonitorSt
     *
     * @mbg.generated Fri Dec 07 14:58:27 CST 2018
     */
    private String mantMonitorSt;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column reqbasedatetvm.ECUSt
     *
     * @mbg.generated Fri Dec 07 14:58:27 CST 2018
     */
    private String ECUSt;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column reqbasedatetvm.ioModuleSt
     *
     * @mbg.generated Fri Dec 07 14:58:27 CST 2018
     */
    private String ioModuleSt;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column reqbasedatetvm.powerModuleSt
     *
     * @mbg.generated Fri Dec 07 14:58:27 CST 2018
     */
    private String powerModuleSt;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column reqbasedatetvm.upsCapacitySt
     *
     * @mbg.generated Fri Dec 07 14:58:27 CST 2018
     */
    private String upsCapacitySt;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column reqbasedatetvm.storageSt
     *
     * @mbg.generated Fri Dec 07 14:58:27 CST 2018
     */
    private String storageSt;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column reqbasedatetvm.invalSjtBoxSt
     *
     * @mbg.generated Fri Dec 07 14:58:27 CST 2018
     */
    private String invalSjtBoxSt;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column reqbasedatetvm.sjtBox1St
     *
     * @mbg.generated Fri Dec 07 14:58:27 CST 2018
     */
    private String sjtBox1St;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column reqbasedatetvm.sjtBox2St
     *
     * @mbg.generated Fri Dec 07 14:58:27 CST 2018
     */
    private String sjtBox2St;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column reqbasedatetvm.sjtRetrievBoxSt
     *
     * @mbg.generated Fri Dec 07 14:58:27 CST 2018
     */
    private String sjtRetrievBoxSt;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column reqbasedatetvm.coinChBox1St
     *
     * @mbg.generated Fri Dec 07 14:58:27 CST 2018
     */
    private String coinChBox1St;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column reqbasedatetvm.coinChBox2St
     *
     * @mbg.generated Fri Dec 07 14:58:27 CST 2018
     */
    private String coinChBox2St;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column reqbasedatetvm.CSCReader1St
     *
     * @mbg.generated Fri Dec 07 14:58:27 CST 2018
     */
    private String CSCReader1St;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column reqbasedatetvm.CSCReader2ST
     *
     * @mbg.generated Fri Dec 07 14:58:27 CST 2018
     */
    private String CSCReader2ST;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column reqbasedatetvm.sign
     *
     * @mbg.generated Fri Dec 07 14:58:27 CST 2018
     */
    private String sign;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table reqbasedatetvm
     *
     * @mbg.generated Fri Dec 07 14:58:27 CST 2018
     */
    private static final long serialVersionUID = 1L;

   
    public String getVer() {
        return ver;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column reqbasedatetvm.ver
     *
     * @param ver the value for reqbasedatetvm.ver
     *
     * @mbg.generated Fri Dec 07 14:58:27 CST 2018
     */
    public void setVer(String ver) {
        this.ver = ver == null ? null : ver.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column reqbasedatetvm.requestDate
     *
     * @return the value of reqbasedatetvm.requestDate
     *
     * @mbg.generated Fri Dec 07 14:58:27 CST 2018
     */
    public String getRequestDate() {
        return requestDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column reqbasedatetvm.requestDate
     *
     * @param requestDate the value for reqbasedatetvm.requestDate
     *
     * @mbg.generated Fri Dec 07 14:58:27 CST 2018
     */
    public void setRequestDate(String requestDate) {
        this.requestDate = requestDate;
    }

   

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column reqbasedatetvm.deviceId
     *
     * @return the value of reqbasedatetvm.deviceId
     *
     * @mbg.generated Fri Dec 07 14:58:27 CST 2018
     */
    public String getDeviceId() {
        return deviceId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column reqbasedatetvm.deviceId
     *
     * @param deviceId the value for reqbasedatetvm.deviceId
     *
     * @mbg.generated Fri Dec 07 14:58:27 CST 2018
     */
    public void setDeviceId(String deviceId) {
        this.deviceId = deviceId == null ? null : deviceId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column reqbasedatetvm.devStatus
     *
     * @return the value of reqbasedatetvm.devStatus
     *
     * @mbg.generated Fri Dec 07 14:58:27 CST 2018
     */
    public String getDevStatus() {
        return devStatus;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column reqbasedatetvm.devStatus
     *
     * @param devStatus the value for reqbasedatetvm.devStatus
     *
     * @mbg.generated Fri Dec 07 14:58:27 CST 2018
     */
    public void setDevStatus(String devStatus) {
        this.devStatus = devStatus == null ? null : devStatus.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column reqbasedatetvm.noteAcceptSt
     *
     * @return the value of reqbasedatetvm.noteAcceptSt
     *
     * @mbg.generated Fri Dec 07 14:58:27 CST 2018
     */
    public String getNoteAcceptSt() {
        return noteAcceptSt;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column reqbasedatetvm.noteAcceptSt
     *
     * @param noteAcceptSt the value for reqbasedatetvm.noteAcceptSt
     *
     * @mbg.generated Fri Dec 07 14:58:27 CST 2018
     */
    public void setNoteAcceptSt(String noteAcceptSt) {
        this.noteAcceptSt = noteAcceptSt == null ? null : noteAcceptSt.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column reqbasedatetvm.coinAcceptSt
     *
     * @return the value of reqbasedatetvm.coinAcceptSt
     *
     * @mbg.generated Fri Dec 07 14:58:27 CST 2018
     */
    public String getCoinAcceptSt() {
        return coinAcceptSt;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column reqbasedatetvm.coinAcceptSt
     *
     * @param coinAcceptSt the value for reqbasedatetvm.coinAcceptSt
     *
     * @mbg.generated Fri Dec 07 14:58:27 CST 2018
     */
    public void setCoinAcceptSt(String coinAcceptSt) {
        this.coinAcceptSt = coinAcceptSt == null ? null : coinAcceptSt.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column reqbasedatetvm.sjtAcceptSt
     *
     * @return the value of reqbasedatetvm.sjtAcceptSt
     *
     * @mbg.generated Fri Dec 07 14:58:27 CST 2018
     */

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column reqbasedatetvm.changedSt
     *
     * @return the value of reqbasedatetvm.changedSt
     *
     * @mbg.generated Fri Dec 07 14:58:27 CST 2018
     */
    public String getChangedSt() {
        return changedSt;
    }

    public String getSjtSaleSt() {
		return sjtSaleSt;
	}

	public void setSjtSaleSt(String sjtSaleSt) {
		this.sjtSaleSt = sjtSaleSt;
	}

	/**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column reqbasedatetvm.changedSt
     *
     * @param changedSt the value for reqbasedatetvm.changedSt
     *
     * @mbg.generated Fri Dec 07 14:58:27 CST 2018
     */
    public void setChangedSt(String changedSt) {
        this.changedSt = changedSt == null ? null : changedSt.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column reqbasedatetvm.sjiMOduleSt
     *
     * @return the value of reqbasedatetvm.sjiMOduleSt
     *
     * @mbg.generated Fri Dec 07 14:58:27 CST 2018
     */
    public String getSjiMOduleSt() {
        return sjiMOduleSt;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column reqbasedatetvm.sjiMOduleSt
     *
     * @param sjiMOduleSt the value for reqbasedatetvm.sjiMOduleSt
     *
     * @mbg.generated Fri Dec 07 14:58:27 CST 2018
     */
    public void setSjiMOduleSt(String sjiMOduleSt) {
        this.sjiMOduleSt = sjiMOduleSt == null ? null : sjiMOduleSt.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column reqbasedatetvm.noteModuleSt
     *
     * @return the value of reqbasedatetvm.noteModuleSt
     *
     * @mbg.generated Fri Dec 07 14:58:27 CST 2018
     */
    public String getNoteModuleSt() {
        return noteModuleSt;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column reqbasedatetvm.noteModuleSt
     *
     * @param noteModuleSt the value for reqbasedatetvm.noteModuleSt
     *
     * @mbg.generated Fri Dec 07 14:58:27 CST 2018
     */
    public void setNoteModuleSt(String noteModuleSt) {
        this.noteModuleSt = noteModuleSt == null ? null : noteModuleSt.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column reqbasedatetvm.noteBoxSt
     *
     * @return the value of reqbasedatetvm.noteBoxSt
     *
     * @mbg.generated Fri Dec 07 14:58:27 CST 2018
     */
    public String getNoteBoxSt() {
        return noteBoxSt;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column reqbasedatetvm.noteBoxSt
     *
     * @param noteBoxSt the value for reqbasedatetvm.noteBoxSt
     *
     * @mbg.generated Fri Dec 07 14:58:27 CST 2018
     */
    public void setNoteBoxSt(String noteBoxSt) {
        this.noteBoxSt = noteBoxSt == null ? null : noteBoxSt.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column reqbasedatetvm.coinModuleSt
     *
     * @return the value of reqbasedatetvm.coinModuleSt
     *
     * @mbg.generated Fri Dec 07 14:58:27 CST 2018
     */
    public String getCoinModuleSt() {
        return coinModuleSt;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column reqbasedatetvm.coinModuleSt
     *
     * @param coinModuleSt the value for reqbasedatetvm.coinModuleSt
     *
     * @mbg.generated Fri Dec 07 14:58:27 CST 2018
     */
    public void setCoinModuleSt(String coinModuleSt) {
        this.coinModuleSt = coinModuleSt == null ? null : coinModuleSt.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column reqbasedatetvm.coinBoxSt
     *
     * @return the value of reqbasedatetvm.coinBoxSt
     *
     * @mbg.generated Fri Dec 07 14:58:27 CST 2018
     */
    public String getCoinBoxSt() {
        return coinBoxSt;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column reqbasedatetvm.coinBoxSt
     *
     * @param coinBoxSt the value for reqbasedatetvm.coinBoxSt
     *
     * @mbg.generated Fri Dec 07 14:58:27 CST 2018
     */
    public void setCoinBoxSt(String coinBoxSt) {
        this.coinBoxSt = coinBoxSt == null ? null : coinBoxSt.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column reqbasedatetvm.touchSt
     *
     * @return the value of reqbasedatetvm.touchSt
     *
     * @mbg.generated Fri Dec 07 14:58:27 CST 2018
     */
    public String getTouchSt() {
        return touchSt;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column reqbasedatetvm.touchSt
     *
     * @param touchSt the value for reqbasedatetvm.touchSt
     *
     * @mbg.generated Fri Dec 07 14:58:27 CST 2018
     */
    public void setTouchSt(String touchSt) {
        this.touchSt = touchSt == null ? null : touchSt.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column reqbasedatetvm.mantMonitorSt
     *
     * @return the value of reqbasedatetvm.mantMonitorSt
     *
     * @mbg.generated Fri Dec 07 14:58:27 CST 2018
     */
    public String getMantMonitorSt() {
        return mantMonitorSt;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column reqbasedatetvm.mantMonitorSt
     *
     * @param mantMonitorSt the value for reqbasedatetvm.mantMonitorSt
     *
     * @mbg.generated Fri Dec 07 14:58:27 CST 2018
     */
    public void setMantMonitorSt(String mantMonitorSt) {
        this.mantMonitorSt = mantMonitorSt == null ? null : mantMonitorSt.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column reqbasedatetvm.ECUSt
     *
     * @return the value of reqbasedatetvm.ECUSt
     *
     * @mbg.generated Fri Dec 07 14:58:27 CST 2018
     */
    public String getECUSt() {
        return ECUSt;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column reqbasedatetvm.ECUSt
     *
     * @param ECUSt the value for reqbasedatetvm.ECUSt
     *
     * @mbg.generated Fri Dec 07 14:58:27 CST 2018
     */
    public void setECUSt(String ECUSt) {
        this.ECUSt = ECUSt == null ? null : ECUSt.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column reqbasedatetvm.ioModuleSt
     *
     * @return the value of reqbasedatetvm.ioModuleSt
     *
     * @mbg.generated Fri Dec 07 14:58:27 CST 2018
     */
    public String getIoModuleSt() {
        return ioModuleSt;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column reqbasedatetvm.ioModuleSt
     *
     * @param ioModuleSt the value for reqbasedatetvm.ioModuleSt
     *
     * @mbg.generated Fri Dec 07 14:58:27 CST 2018
     */
    public void setIoModuleSt(String ioModuleSt) {
        this.ioModuleSt = ioModuleSt == null ? null : ioModuleSt.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column reqbasedatetvm.powerModuleSt
     *
     * @return the value of reqbasedatetvm.powerModuleSt
     *
     * @mbg.generated Fri Dec 07 14:58:27 CST 2018
     */
    public String getPowerModuleSt() {
        return powerModuleSt;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column reqbasedatetvm.powerModuleSt
     *
     * @param powerModuleSt the value for reqbasedatetvm.powerModuleSt
     *
     * @mbg.generated Fri Dec 07 14:58:27 CST 2018
     */
    public void setPowerModuleSt(String powerModuleSt) {
        this.powerModuleSt = powerModuleSt == null ? null : powerModuleSt.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column reqbasedatetvm.upsCapacitySt
     *
     * @return the value of reqbasedatetvm.upsCapacitySt
     *
     * @mbg.generated Fri Dec 07 14:58:27 CST 2018
     */
    public String getUpsCapacitySt() {
        return upsCapacitySt;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column reqbasedatetvm.upsCapacitySt
     *
     * @param upsCapacitySt the value for reqbasedatetvm.upsCapacitySt
     *
     * @mbg.generated Fri Dec 07 14:58:27 CST 2018
     */
    public void setUpsCapacitySt(String upsCapacitySt) {
        this.upsCapacitySt = upsCapacitySt == null ? null : upsCapacitySt.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column reqbasedatetvm.storageSt
     *
     * @return the value of reqbasedatetvm.storageSt
     *
     * @mbg.generated Fri Dec 07 14:58:27 CST 2018
     */
    public String getStorageSt() {
        return storageSt;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column reqbasedatetvm.storageSt
     *
     * @param storageSt the value for reqbasedatetvm.storageSt
     *
     * @mbg.generated Fri Dec 07 14:58:27 CST 2018
     */
    public void setStorageSt(String storageSt) {
        this.storageSt = storageSt == null ? null : storageSt.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column reqbasedatetvm.invalSjtBoxSt
     *
     * @return the value of reqbasedatetvm.invalSjtBoxSt
     *
     * @mbg.generated Fri Dec 07 14:58:27 CST 2018
     */
    public String getInvalSjtBoxSt() {
        return invalSjtBoxSt;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column reqbasedatetvm.invalSjtBoxSt
     *
     * @param invalSjtBoxSt the value for reqbasedatetvm.invalSjtBoxSt
     *
     * @mbg.generated Fri Dec 07 14:58:27 CST 2018
     */
    public void setInvalSjtBoxSt(String invalSjtBoxSt) {
        this.invalSjtBoxSt = invalSjtBoxSt == null ? null : invalSjtBoxSt.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column reqbasedatetvm.sjtBox1St
     *
     * @return the value of reqbasedatetvm.sjtBox1St
     *
     * @mbg.generated Fri Dec 07 14:58:27 CST 2018
     */
    public String getSjtBox1St() {
        return sjtBox1St;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column reqbasedatetvm.sjtBox1St
     *
     * @param sjtBox1St the value for reqbasedatetvm.sjtBox1St
     *
     * @mbg.generated Fri Dec 07 14:58:27 CST 2018
     */
    public void setSjtBox1St(String sjtBox1St) {
        this.sjtBox1St = sjtBox1St == null ? null : sjtBox1St.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column reqbasedatetvm.sjtBox2St
     *
     * @return the value of reqbasedatetvm.sjtBox2St
     *
     * @mbg.generated Fri Dec 07 14:58:27 CST 2018
     */
    public String getSjtBox2St() {
        return sjtBox2St;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column reqbasedatetvm.sjtBox2St
     *
     * @param sjtBox2St the value for reqbasedatetvm.sjtBox2St
     *
     * @mbg.generated Fri Dec 07 14:58:27 CST 2018
     */
    public void setSjtBox2St(String sjtBox2St) {
        this.sjtBox2St = sjtBox2St == null ? null : sjtBox2St.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column reqbasedatetvm.sjtRetrievBoxSt
     *
     * @return the value of reqbasedatetvm.sjtRetrievBoxSt
     *
     * @mbg.generated Fri Dec 07 14:58:27 CST 2018
     */
    public String getSjtRetrievBoxSt() {
        return sjtRetrievBoxSt;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column reqbasedatetvm.sjtRetrievBoxSt
     *
     * @param sjtRetrievBoxSt the value for reqbasedatetvm.sjtRetrievBoxSt
     *
     * @mbg.generated Fri Dec 07 14:58:27 CST 2018
     */
    public void setSjtRetrievBoxSt(String sjtRetrievBoxSt) {
        this.sjtRetrievBoxSt = sjtRetrievBoxSt == null ? null : sjtRetrievBoxSt.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column reqbasedatetvm.coinChBox1St
     *
     * @return the value of reqbasedatetvm.coinChBox1St
     *
     * @mbg.generated Fri Dec 07 14:58:27 CST 2018
     */
    public String getCoinChBox1St() {
        return coinChBox1St;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column reqbasedatetvm.coinChBox1St
     *
     * @param coinChBox1St the value for reqbasedatetvm.coinChBox1St
     *
     * @mbg.generated Fri Dec 07 14:58:27 CST 2018
     */
    public void setCoinChBox1St(String coinChBox1St) {
        this.coinChBox1St = coinChBox1St == null ? null : coinChBox1St.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column reqbasedatetvm.coinChBox2St
     *
     * @return the value of reqbasedatetvm.coinChBox2St
     *
     * @mbg.generated Fri Dec 07 14:58:27 CST 2018
     */
    public String getCoinChBox2St() {
        return coinChBox2St;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column reqbasedatetvm.coinChBox2St
     *
     * @param coinChBox2St the value for reqbasedatetvm.coinChBox2St
     *
     * @mbg.generated Fri Dec 07 14:58:27 CST 2018
     */
    public void setCoinChBox2St(String coinChBox2St) {
        this.coinChBox2St = coinChBox2St == null ? null : coinChBox2St.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column reqbasedatetvm.CSCReader1St
     *
     * @return the value of reqbasedatetvm.CSCReader1St
     *
     * @mbg.generated Fri Dec 07 14:58:27 CST 2018
     */
    public String getCSCReader1St() {
        return CSCReader1St;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column reqbasedatetvm.CSCReader1St
     *
     * @param CSCReader1St the value for reqbasedatetvm.CSCReader1St
     *
     * @mbg.generated Fri Dec 07 14:58:27 CST 2018
     */
    public void setCSCReader1St(String CSCReader1St) {
        this.CSCReader1St = CSCReader1St == null ? null : CSCReader1St.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column reqbasedatetvm.CSCReader2ST
     *
     * @return the value of reqbasedatetvm.CSCReader2ST
     *
     * @mbg.generated Fri Dec 07 14:58:27 CST 2018
     */
    public String getCSCReader2ST() {
        return CSCReader2ST;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column reqbasedatetvm.CSCReader2ST
     *
     * @param CSCReader2ST the value for reqbasedatetvm.CSCReader2ST
     *
     * @mbg.generated Fri Dec 07 14:58:27 CST 2018
     */
    public void setCSCReader2ST(String CSCReader2ST) {
        this.CSCReader2ST = CSCReader2ST == null ? null : CSCReader2ST.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column reqbasedatetvm.sign
     *
     * @return the value of reqbasedatetvm.sign
     *
     * @mbg.generated Fri Dec 07 14:58:27 CST 2018
     */
    public String getSign() {
        return sign;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column reqbasedatetvm.sign
     *
     * @param sign the value for reqbasedatetvm.sign
     *
     * @mbg.generated Fri Dec 07 14:58:27 CST 2018
     */
    public void setSign(String sign) {
        this.sign = sign == null ? null : sign.trim();
    }
}